#!/bin/bash

echo "<RCC>" > _resources.qrc
echo "  <qresource>" >> _resources.qrc

for f in icons/*; do
    echo "    <file>${f}</file>" >> _resources.qrc
done

echo "  </qresource>" >> _resources.qrc
echo "</RCC>" >> _resources.qrc

pyrcc5 -o ../chemcanvas/resources_rc.py _resources.qrc

if [ $? -eq 0 ]; then
    echo "Compiled Resources saved as ../chemcanvas/resources_rc.py"
else
    echo "Failed to compile resources"
fi

rm _resources.qrc
