name: Build Packages
on:
  release:
    types: [published]

# required for uploading assets
permissions:
  contents: write

jobs:
  flatpak:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Flatpak
        run: |
          sudo apt install flatpak flatpak-builder
          flatpak --user remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          flatpak-builder --force-clean --repo=repo --user --install-deps-from=flathub builddir io.github.ksharindam.chemcanvas.yaml
          flatpak build-bundle repo ChemCanvas.flatpak io.github.ksharindam.chemcanvas --runtime-repo=https://flathub.org/repo/flathub.flatpakrepo

      - name: Upload Release Assets
        uses: AButler/upload-release-assets@v3.0
        with:
          files: "ChemCanvas.flatpak"
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  snap:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Snap
        uses: snapcore/action-build@v1
        id: build-snap

      - name: Publish to Snap Store
        uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_LOGIN }}
        with:
          snap: ${{ steps.build.outputs.snap }}
          release: stable

      - name: Rename Snap
        run: |
          mv "${{ steps.build-snap.outputs.snap }}" ChemCanvas.snap

      - name: Upload Release Assets
        uses: AButler/upload-release-assets@v3.0
        with:
          files: ChemCanvas.snap
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  exe:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v5
        with:
          python-version: '3.8.7'

      - name: Install Dependencies
        run: |
          pip3 install PyQt5
          pip3 install pyinstaller

      - name: Build ChemCanvas
        run: |
          pyrcc5 -o ./chemcanvas/resources_rc.py ./data/resources.qrc
          pyuic5 -o ./chemcanvas/ui_mainwindow.py ./data/mainwindow.ui
          cd Windows
          pyinstaller chemcanvas.spec

      - name: Create Exe Installer
        uses: joncloud/makensis-action@v4.1
        with:
          script-file: ./Windows/ChemCanvas.nsi

      - name: Upload Release Assets
        uses: AButler/upload-release-assets@v3.0
        with:
          files: "Windows/*.exe"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
